export const INICIAR_SESION = "INICIAR_SESION";
export const CERRAR_SESION = "CERRAR_SESION";
export const LIMPIAR_SESION = "LIMPIAR_SESION";

export const SET_CONTROL_ES = "SET_CONTROL_ES";
export const SET_RECEPCIONISTAS = "SET_RECEPCIONISTAS";

export const ELIMINAR_EMPLEADO = "ELIMINAR_EMPLEADO";

export const SET_ESPECIALIDADES = "SET_ESPECIALIDADES";
export const SET_CANTIDAD_GENTE = "SET_CANTIDAD_GENTE";
