export const ADMIN_SUCURSAL = "ADMIN_SUCURSAL"
export const ADMIN_GENERAL = "ADMIN_GENERAL"
export const EMPLEADO = "EMPLEADO"

export const CONTROL_ES = "CONTROL_ES"
export const RECEPCION = "RECEPCION"