export const INICIAR_SESION = "INICIAR_SESION";
export const CERRAR_SESION = "CERRAR_SESION";
export const ACTUALIZAR_TURNOS = "ACTUALIZAR_TURNOS"
export const LIMPIAR_SESION = "LIMPIAR_SESION"
export const OBTENER_ESPECIALIDADES = "OBTENER_ESPECIALIDADES"