export const INICIAR_SESION = "INICIAR_SESION";
export const CERRAR_SESION = "CERRAR_SESION";
export const ACTUALIZAR_TURNOS = "ACTUALIZAR_TURNOS"
export const SET_SUCURSALES = "SET_SUCURSALES"
export const LIMPIAR_SESION = "LIMPIAR_SESION"
export const OBTENER_ESPECIALIDADES = "OBTENER_ESPECIALIDADES"
export const SET_ESPECIALIDAD = "SET_ESPECIALIDAD"
export const SET_COORDENADAS = "SET_COORDENADAS"

export const CALCULAR_DISTANCIA = "CALCULAR_DISTANCIA"

export const FILTRAR_CANTIDAD = "FILTRAR_CANTIDAD"
export const FILTRAR_DISTANCIA = "FILTRAR_DISTANCIA"
export const FILTRAR_NOMBRE = "FILTRAR_NOMBRE"

export const SET_FILTRO = "SET_FILTRO"